# Generated by Django 3.2.5 on 2022-04-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_item_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
